Modified README.md and found a bug
Thenlie/readme-generator pull request #22
Opened 2024-01-28 14:37 UTC by Axwaizee

modified the readme file where in Installation part

it was mentioned

```bash
git clone git@github.com:Thenlie/readme-generator.git
```

where many users don't use SSH so they may get error and end up with nothing. So, I added an OR operator 

```bash
git clone git@github.com:Thenlie/readme-generator.git || git clone https://github.com/Thenlie/readme-generator.git
```

now if the first command gets error then the 2nd one will surely work.
Also, while editing and replicating the instruction for installation and running the application i found that the 
command 

```bash
node index.js
```

won't work because the index.js file is no more on the root directory

![image](https://github.com/Thenlie/readme-generator/assets/83546692/77a988d2-0422-467a-8ed1-4cb9b3fa6837)

it's in the `/dist` directory.

Also, while executing or creating my `README.md` file i used `npm start` **NOT** `node index.js`.

![image](https://github.com/Thenlie/readme-generator/assets/83546692/4012e43e-6f8b-476a-add3-4316fcbebb2f)

You have already described the Usage in Installation part with `npm start` and in the Usage portion is wrong so you make changes to it accordingly. Maybe its because you never updated the readme file later also the gif/video in the Usage part needs to be updated.

Thank you
Ahh! typed so long hope they gets fixed soon.

2024-01-28 16:24 UTC, Thenlie requested changes
Thank you for the feedback here! Definitely missed some updates in the README after converting this project to TypeScript. 

I think the main error you pointed out is actually missing from this PR. The "Usage" step should be updated to say, "After using the `npm start` command..."

2024-01-28 16:24 UTC, Thenlie commented on README.md
> +  ```
I think this step is fine, it is the Usage step that has the error.

2024-01-28 16:24 UTC, Thenlie commented on README.md
> +  git clone git@github.com:Thenlie/readme-generator.git || git clone https://github.com/Thenlie/readme-generator.git
I think I would prefer something like:
---
Use the steps below to clone the repository and get the project running on your local machine.

1. Navigate to the develop branch of the repository and click the green "Code" button. Then copy the repository URL with the method of your choosing. We suggest SSH which can be setup be following [these docs](https://docs.github.com/en/authentication/connecting-to-github-with-ssh).

2. Go to your terminal program of choice and navigate the the folder you want the project to live in. Then run the command below to clone the repository:

```sh
git clone <repository_url>
```
---
This let's the user know that we are showing steps for SSH, but still gives them the flexibility to choose HTTPS.

2024-01-29 12:36 UTC, Axwaizee commented
Okay, I made various changes to the file, you may review and merge it. If anything need to be corrected or modified then let me know.

Thank you.

2024-01-30 04:39 UTC, Thenlie requested changes
These changes break the table of contents since they alter the markdown headings. I think I would prefer to stick to the initial commit and just update the one or two things pointed out in the first review. I don't think a comprehensive guide on how to copy the project is necessary since GitHub already has great documentation on how to do that. If you disagree, I am happy to hear your reasoning.

2024-01-30 12:21 UTC, Axwaizee commented
Have a look at this:

![image](https://github.com/Thenlie/readme-generator/assets/83546692/950b6859-7154-419b-882d-d2d5e81c2385)

If this is alright then you may go with PR.

Any other changes would be appreciated.

2024-08-29 00:32 UTC, Thenlie approved these changes

2024-08-29 00:32 UTC, merged

2024-08-29 00:32 UTC, Thenlie commented
@Axwaizee Sorry I forgot about this! 😅